### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by erickveil** [erickveil/VagusPurr#1]
- [x] Design and add icons
    - [x] Smoke test and make sure icons work. 
- [x] Create Store page
- [x] Generate store page graphics
- [x] Upload abb and release
